"""create_chunk_embedding_tables

Revision ID: 2b0cc9b4cfe4
Revises: ae6c1d599e02
Create Date: 2026-02-16 20:19:29.469740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0cc9b4cfe4'
down_revision: Union[str, None] = 'ae6c1d599e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_sets',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=False),
    sa.Column('distance', sa.String(length=32), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_embedding_sets_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_sets')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_embedding_sets_workspace_name')
    )
    with op.batch_alter_table('embedding_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_sets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('chunks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=65536), nullable=True),
    sa.Column('text_uri', sa.String(length=2048), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_hash', name='uq_chunks_document_hash')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_chunk_hash'), ['chunk_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_set_id', sa.String(length=36), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=256), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_chunk_embeddings_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_set_id'], ['embedding_sets.id'], name=op.f('fk_chunk_embeddings_embedding_set_id_embedding_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_embeddings')),
    sa.UniqueConstraint('chunk_id', 'embedding_set_id', name='uq_chunk_embeddings_chunk_set')
    )
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunk_embeddings_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunk_embeddings_embedding_set_id'), ['embedding_set_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunk_embeddings_embedding_set_id'))
        batch_op.drop_index(batch_op.f('ix_chunk_embeddings_chunk_id'))

    op.drop_table('chunk_embeddings')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_chunk_hash'))

    op.drop_table('chunks')
    with op.batch_alter_table('embedding_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_sets_workspace_id'))

    op.drop_table('embedding_sets')
    # ### end Alembic commands ###
