"""create_runs_events_tables

Revision ID: 3bc92cf2f9ff
Revises: 2b0cc9b4cfe4
Create Date: 2026-02-16 20:23:09.914067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc92cf2f9ff'
down_revision: Union[str, None] = '2b0cc9b4cfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_runs_workspace_id_started_at', ['workspace_id', 'started_at'], unique=False)

    op.create_table('events',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_events_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_events_run_id_ts', ['run_id', 'ts'], unique=False)

    op.create_table('run_items',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('metrics_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_items_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_items')),
    sa.UniqueConstraint('run_id', 'stage', 'target_type', 'target_id', name='uq_run_items_run_stage_target')
    )
    with op.batch_alter_table('run_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_items_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_run_items_run_stage_status', ['run_id', 'stage', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_items', schema=None) as batch_op:
        batch_op.drop_index('ix_run_items_run_stage_status')
        batch_op.drop_index(batch_op.f('ix_run_items_run_id'))

    op.drop_table('run_items')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_run_id_ts')
        batch_op.drop_index(batch_op.f('ix_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_workspace_id_started_at')
        batch_op.drop_index(batch_op.f('ix_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))

    op.drop_table('runs')
    # ### end Alembic commands ###
