"""create_query_logs_tables

Revision ID: 82aaac20c4c7
Revises: 3bc92cf2f9ff
Create Date: 2026-02-16 20:25:04.869118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82aaac20c4c7'
down_revision: Union[str, None] = '3bc92cf2f9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_text', sa.String(length=65536), nullable=False),
    sa.Column('embedding_set_id', sa.String(length=36), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('filters_json', sa.String(length=4096), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_queries_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries'))
    )
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queries_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_queries_workspace_id_ts', ['workspace_id', 'ts'], unique=False)

    op.create_table('query_results',
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_query_results_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_query_results_query_id_queries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_results')),
    sa.UniqueConstraint('query_id', 'rank', name='uq_query_results_query_rank')
    )
    with op.batch_alter_table('query_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_results_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_results_query_id'), ['query_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_results_query_id'))
        batch_op.drop_index(batch_op.f('ix_query_results_chunk_id'))

    op.drop_table('query_results')
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_index('ix_queries_workspace_id_ts')
        batch_op.drop_index(batch_op.f('ix_queries_workspace_id'))

    op.drop_table('queries')
    # ### end Alembic commands ###
