"""create_core_lineage_tables

Revision ID: ae6c1d599e02
Revises: 9d7215df81c7
Create Date: 2026-02-16 20:15:03.929666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6c1d599e02'
down_revision: Union[str, None] = '9d7215df81c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('name', name=op.f('uq_workspaces_name'))
    )
    op.create_table('sources',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('external_ref', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sources_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source_versions',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_meta_json', sa.String(length=4096), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_versions_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_versions'))
    )
    with op.batch_alter_table('source_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_versions_content_sha256'), ['content_sha256'], unique=True)

    op.create_table('documents',
    sa.Column('source_version_id', sa.String(length=36), nullable=False),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('structure_json_uri', sa.String(length=2048), nullable=False),
    sa.Column('plain_text_uri', sa.String(length=2048), nullable=True),
    sa.Column('stats_json', sa.String(length=8192), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], name=op.f('fk_documents_source_version_id_source_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('source_version_id', 'extractor', 'extractor_version', name='uq_documents_source_version_extractor')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_source_version_id'), ['source_version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_version_id'))

    op.drop_table('documents')
    with op.batch_alter_table('source_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_versions_content_sha256'))

    op.drop_table('source_versions')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_workspace_id'))

    op.drop_table('sources')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
