"""Error codes for docling pipeline (Appendix B taxonomy)."""
from enum import StrEnum


class DoclingErrorCode(StrEnum):
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    TOO_MANY_PAGES = "TOO_MANY_PAGES"
    STORAGE_READ_FAILED = "STORAGE_READ_FAILED"
    STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
    PARSE_FAILED = "PARSE_FAILED"
    EXPORT_FAILED = "EXPORT_FAILED"
    CHUNK_FAILED = "CHUNK_FAILED"
    TOO_MANY_CHUNKS = "TOO_MANY_CHUNKS"
    TIMEOUT_PARSE = "TIMEOUT_PARSE"
    TIMEOUT_CHUNK = "TIMEOUT_CHUNK"
    DB_WRITE_FAILED = "DB_WRITE_FAILED"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
